project_id = "etvwehduvabeokhonhdf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://etvwehduvabeokhonhdf.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[edge_functions]
enabled = true
port = 54323

[functions.process-order]
verify_jwt = true

[functions.send-notification]  
verify_jwt = false

[realtime]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325