// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcorxyfvllsdhtojthch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jb3J4eWZ2bGxzZGh0b2p0aGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzI5MzgsImV4cCI6MjA3MjUwODkzOH0.hV9kQZNCp-a69fc64D1gNLUws5kFk0Z7Cpe3smuChEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});